module.exports = {
  id: {
    automod: "🛡️",
    autorole: "💚",
    moderation: "🛠️",
    ignore: "👤",
    music: "🎵",
    nightmode: "🌌",
    premium: "💎",
    giveaway: "🎉",
    owner: "👤",
    boost: "👤",
    welcome: "👋",
    ticket: "🎟️",
    information: "🔍",
    utility: "🔧",
    greet: "👤",
    sticky: "🔥",
    ai: "💎",
    vanity: "🔗"
  },
  badges: {
    owner: "👑",
    dev: "👨‍💻",
    admin: "👮‍♂️",
    staff: "👨‍👩‍👧‍👦",
    partner: "🤝",
    supporter: "❤️",
    sponsor: "🎖️",
    os: "🤝",
    vip: "🌟",
    friend: "👫",
    bug: "🐛"
  },
  util: {
      enabled: "✅",
      disabled: "❌",
      enabler: "✅",
      disabler: "❌",
      arrow: "➡️",
      tick: "✔️",
      cross: "❌",
      loading: "⏳",
  },
  flag: {
      nitro: "💎",
      booster: "🚀",
      hypesquad: "🎉",
      hype1: "🌟",
      hype2: "💪",
      hype3: "⚖️",
      bug1: "🐛",
      bug2: "🐛",
      verifieddev: "✅",
      partner: "🤝",
      activedev: "👨‍💻",
      verifiedbot: "🤖",
      staff: "👨‍👩‍👧‍👦",
  }
};